### ISSUE TITLE
Data view error

### ISSUE THREAD

**Issue by JaredKIso** [Elania/12weekyear#2]
Trying to set this up and I am getting a data view error:
![image](https://github.com/user-attachments/assets/d843ad38-bd13-449e-89e2-7fe62484b0cb)

I have the .js file in "99 - Meta\scripts" and have the folder being called in CustomJS plugin.

I have dataview enabled and JS enabled in that as well.

The error happens when I try to paste it into my weekly template and it just fails. I have tested different folder paths as well and still the same error.

Would appreciate the insight so I can fix this as I look forward to using it, thank you :)

**Comment by JaredKIso** [comment]
Now have this error:

![image](https://github.com/user-attachments/assets/5f1b31bb-7fac-45da-a20a-25d45f892f68)

**Comment by Air000** [comment]
Hi, can you explain how you finally solve this problem? I encounter the same issue
